### ISSUE TITLE
deepmerge component not available

### ISSUE THREAD

**Issue by tariqinaam** [ooyala/html5-skin#730]
After upgrading html5-skin to 4.11.13/14 from 4.10.6, I get error of 'deepmerge is not a function'
I tried to isolate this issue and it seems if there is requirejs is on the page, then this specific error occur. I am not loading html5-skin or other ooyala player component via requirejs.
Same site work fine with 4.10.6

Exact console log error is:
`Uncaught TypeError: DeepMerge is not a function
    at Html5Skin.loadConfigData (html5-skin.js:6306)

    at Html5Skin.<anonymous> (html5-skin.js:5727)
    at fire (core.js:2247)
    at Object.fireWith [as resolveWith] (core.js:2357)
    at done (core.js:9076)
    at XMLHttpRequest.callback (core.js:9791)`

**Comment by mistermendez** [comment]
Try `npm install`.

`deepMerge` was added as a [dependency in `package.json`](https://github.com/ooyala/html5-skin/blob/stable/package.json#L23) in 4.11.13.

**Comment by tariqinaam** [comment]
I did try npm install and it stil couldn't fix. 
When I try load html5-skin via requirejs, it throws 
`Mismatched anonymous define() module: function ()`
I think this is more of a deepmerge library issue with requirejs..  Just wondering if anyone tried to use it requirejs.

**Comment by tariqinaam** [comment]
I have tried all possible way but it doesn't work with requirejs.
It complain about deepmerge not available. I have tried bundled html5-skin js as well.

**Comment by spaddon** [comment]
@tariqinaam 

Since there's an incompatibility between deepmerge and Require.js, the html5-skin needs to be loaded separately. Additionally, whenever you load incompatible scripts along with RequireJS, you need to make sure to load the RequireJS script after these other scripts load. More on this here: https://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module

**Comment by TehShrike** [comment]
deepmerge@1.4.0 exposes a CommonJS entry point via the `pkg.browser` field, so if you rebuild with 1.4.0 or later, people using AMD modules shouldn't have any issues.  A pull request is open to bump the version: #759.

**Comment by welikeideas** [comment]
Are there any plans to release a version of the player with deepmerge@1.4.0?

**Comment by alanoooyala** [comment]
This is being discussed. [Our ref: PBW-6804]
