### PR TITLE
Use deepmerge@1.4.0

### LINKED ISSUE #730: deepmerge component not available
After upgrading html5-skin to 4.11.13/14 from 4.10.6, I get error of 'deepmerge is not a function'
I tried to isolate this issue and it seems if there is requirejs is on the page, then this specific error occur. I am not loading html5-skin or other ooyala player component via requirejs.
Same site work fine with 4.10.6

Exact console log error is:
`Uncaught TypeError: DeepMerge is not a function
    at Html5Skin.loadConfigData (html5-skin.js:6306)

    at Html5Skin.<anonymous> (html5-skin.js:5727)
    at fire (core.js:2247)
    at Object.fireWith [as resolveWith] (core.js:2357)
    at done (core.js:9076)
    at XMLHttpRequest.callback (core.js:9791)`

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #730

### CODE REVIEW

**Comment by jpfranco** [comment]
Sorry about the delay @TehShrike, we've been busy with other high priority issues. We've recreated this update in #860 and #861 which have now been merged. We're planning to include this update on our next release unless there are issues found during QA.

**Comment by TehShrike** [comment]
Bangin'. 👍
